"""v14: 'AI will change everything' (2026 edition), 1920x1080.

Reference-style look: light-grey infographics with thin green/red lines, picture-in-picture stock inset,
cinematic stock footage, dark chat screenshots, red 'GENERATED BY AI' tags, end screen.

python3 engine14.py prep | info | still N | video A B out.mp4
"""
import json
import math
import os
import subprocess
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

from script14 import SCRIPT, LINES

W, H, FPS = 1920, 1080, 30
FONT_DIR = "/home/claude/v14/fonts"
FONTS = {"Bold": "FiraSansCondensed-Bold.ttf", "ExtraBold": "FiraSansCondensed-Bold.ttf",
         "SemiBold": "FiraSansCondensed-SemiBold.ttf", "Regular": "FiraSansCondensed-SemiBold.ttf"}

BG = (232, 236, 239)
INK = (28, 32, 38)
GRAY = (112, 120, 132)
LGRAY = (196, 202, 210)
GREEN = (14, 134, 96)
RED = (192, 24, 44)
WHITE = (255, 255, 255)
TAG_RED = (150, 14, 22)
TAG_BLUE = (36, 84, 196)
CHAT_BG = (52, 53, 65)
CHAT_AI = (68, 70, 84)

TM = json.load(open("timing.json"))
D, TW = TM["D"], TM["T"]
LEAD = TM.get("voice_offset", 0.4)
starts = [LEAD + s for s in TM["starts"]]
LAST_END = starts[-1] + D[-1] + 0.9
END_LEN = 9.0
TOTAL = LAST_END + END_LEN
NF = int(TOTAL * FPS)


def ease(x):
    x = min(1.0, max(0.0, x))
    return x * x * (3 - 2 * x)


def out_back(x, s=1.70158):
    x = min(1.0, max(0.0, x))
    return 1 + (s + 1) * (x - 1) ** 3 + s * (x - 1) ** 2


def out_cubic(x):
    x = min(1.0, max(0.0, x))
    return 1 - (1 - x) ** 3


_F = {}


def font(size, weight="Bold"):
    key = (int(size), weight)
    if key not in _F:
        _F[key] = ImageFont.truetype(f"{FONT_DIR}/{FONTS[weight]}", max(1, int(size)))
    return _F[key]


# ------------------------------------------------------------------ shots
POOL = ["office", "servers", "coder", "typing", "robot2", "students", "lab", "chip", "factory", "interview", "filmset",
        "phone", "robot", "airplane", "singer"]
TOPIC = {}


def gen_len(name):
    return 5.0 if name.startswith("gen:ws_") else 4.0
_pool_i = [0]


def pick_broll(line, prev):
    name = TOPIC.get(line)
    if name and name != prev:
        return name
    for _ in range(len(POOL)):
        name = POOL[_pool_i[0] % len(POOL)]
        _pool_i[0] += 1
        if name != prev:
            return name
    return POOL[0]


def build_shots():
    shots = []
    n = len(SCRIPT)
    for i, (text, sc) in enumerate(SCRIPT):
        scs = sc if isinstance(sc, list) else [sc]
        t0 = 0.0 if i == 0 else starts[i] - 0.15
        t1 = (starts[i + 1] - 0.15) if i + 1 < n else LAST_END
        fixed = sum(s.get("d", 0) for s in scs)
        ws = [0 if "d" in s else s.get("w", 1.0) for s in scs]
        tot = sum(ws) or 1
        durs = [s["d"] if "d" in s else (t1 - t0 - fixed) * w / tot for s, w in zip(scs, ws)]
        for k, s in enumerate(scs):  # generated clips are only 4 s long
            if s["t"] == "clip" and s["src"].startswith("gen:") and durs[k] > gen_len(s["src"]):
                extra = durs[k] - gen_len(s["src"])
                durs[k] = gen_len(s["src"])
                others = [j for j, o in enumerate(scs) if j != k and not (o["t"] == "clip" and o["src"].startswith("gen:"))]
                if others:
                    durs[others[0]] += extra
                else:
                    durs[k] += extra
        t = t0
        line_shots = []
        for k, (s, d) in enumerate(zip(scs, durs)):
            line_shots.append(dict(t0=t, t1=t + d, sc=s, line=i, k=k))
            t += d
        out, kk, prev = [], 100, None
        for sh in line_shots:
            d = sh["t1"] - sh["t0"]
            if sh["sc"]["t"] not in ("clip", "title", "quote") and d > 5.8:
                g = min(max(3.4, d * 0.56), d - 2.2)
                nm = pick_broll(i, prev)
                out.append(dict(t0=sh["t0"], t1=sh["t0"] + g, sc=sh["sc"], line=i, k=sh["k"]))
                out.append(dict(t0=sh["t0"] + g, t1=sh["t1"], sc=dict(t="clip", src=nm), line=i, k=kk))
                kk += 1
                prev = nm
            else:
                out.append(sh)
                prev = sh["sc"].get("src") if sh["sc"]["t"] == "clip" else prev
        shots += out
    shots.append(dict(t0=LAST_END, t1=TOTAL, sc=dict(t="endcard"), line=n, k=0))
    return shots


SHOTS = build_shots()


def shot_at(t):
    lo, hi = 0, len(SHOTS) - 1
    while lo < hi:
        mid = (lo + hi) // 2
        if SHOTS[mid]["t1"] <= t:
            lo = mid + 1
        else:
            hi = mid
    return SHOTS[lo]


# ------------------------------------------------------------------ media
def clip_dir(s, suffix=""):
    return f"frames/{s['line']:02d}_{s['k']}{suffix}"


def bars(src):
    out = subprocess.run(["ffmpeg", "-loglevel", "error", "-ss", "1.5", "-i", src, "-frames:v", "1", "-f", "rawvideo",
                          "-pix_fmt", "gray", "-"], capture_output=True).stdout
    probe = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height",
                            "-of", "csv=p=0", src], capture_output=True, text=True).stdout.strip().split(",")
    w, h = int(probe[0]), int(probe[1])
    a = np.frombuffer(out, np.uint8)[: w * h].reshape(h, w).astype(np.float32)
    rows = np.where(a.mean(1) > 12)[0]
    return (int(rows[0]), int(rows[-1]) + 1, w, h) if len(rows) else (0, h, w, h)


_used = {}


def extract(name, out, dur, size=(1920, 1080), grade=True):
    """extract `dur` seconds of clip `name` (stock or gen:) to jpg frames of `size` into dir `out`."""
    os.makedirs(out, exist_ok=True)
    sw, sh = size
    eq = ",eq=contrast=1.04:saturation=1.06" if grade else ""
    if name.startswith("gen:"):
        src = f"gen/{name[4:]}.mp4"
        top, bot, w, h = bars(src)
        ph = bot - top
        cw = min(w, int(ph * 16 / 9))
        ch = int(cw * 9 / 16)
        x0 = (w - cw) // 2
        y0 = top + (ph - ch) // 2
        vf = f"crop={cw}:{ch}:{x0}:{y0},scale={sw}:{sh}:flags=lanczos,fps=30{eq}"
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", src, "-vf", vf, "-frames:v",
                        str(int(min(dur, gen_len(name)) * FPS)), "-start_number", "1", "-q:v", "3", f"{out}/%05d.jpg"],
                       check=True)
        return
    src = f"media/{name}.mp4"
    clen = float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", src],
                                capture_output=True, text=True).stdout.strip() or 0)
    off = _used.get(name, 0.4)
    if off + dur > clen:
        off = max(0, clen - dur - 0.05)
    _used[name] = off + dur
    speed = 1.0 if clen - off >= dur else max(0.3, (clen - off) / dur * 0.98)
    vf = (f"setpts={1 / speed:.4f}*PTS,scale={sw}:{sh}:force_original_aspect_ratio=increase,crop={sw}:{sh},fps=30{eq}")
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-ss", f"{off:.2f}", "-i", src, "-t", f"{dur * speed:.2f}",
                    "-vf", vf, "-frames:v", str(int(dur * FPS) + 2), "-start_number", "1", "-q:v", "3",
                    f"{out}/%05d.jpg"], check=True)


def prep():
    os.makedirs("frames", exist_ok=True)
    os.makedirs("stills", exist_ok=True)
    for s in SHOTS:
        sc = s["sc"]
        dur = s["t1"] - s["t0"] + 0.25
        if sc["t"] == "clip":
            extract(sc["src"], clip_dir(s), dur)
            print("clip", clip_dir(s), flush=True)
        elif sc["t"] == "curve" and sc.get("pip"):
            names = sc["pip"]
            for j, nm in enumerate(names):
                extract(nm, clip_dir(s, f"_pip{j}"), dur / len(names) + 0.3, size=(640, 360), grade=False)
            print("pip", clip_dir(s), flush=True)
        for nm in (sc.get("names") or []) + ([sc["still"]] if sc.get("still") else []):
            path = f"stills/{nm}.jpg"
            if os.path.exists(path):
                continue
            src = f"gen/{nm}.mp4"
            top, bot, w, h = bars(src)
            ph = bot - top
            cw = min(w, int(ph * 16 / 9))
            ch = int(cw * 9 / 16)
            vf = f"crop={cw}:{ch}:{(w - cw) // 2}:{top + (ph - ch) // 2},scale=1280:720:flags=lanczos"
            subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-ss", "2.0", "-i", src, "-vf", vf, "-frames:v", "1",
                            "-q:v", "2", path], check=True)


_NCACHE = {}


def n_frames(d):
    if d not in _NCACHE:
        _NCACHE[d] = len([f for f in os.listdir(d) if f.endswith(".jpg")])
    return _NCACHE[d]


def frame_img(d, t0, t):
    n = n_frames(d)
    i = max(1, min(n, int((t - t0) * FPS) + 1))
    return Image.open(f"{d}/{i:05d}.jpg").convert("RGB")


def clip_frame(s, t):
    img = frame_img(clip_dir(s), s["t0"], t)
    p = (t - s["t0"]) / max(0.01, s["t1"] - s["t0"])
    z = 1.0 + 0.055 * p if s["k"] % 2 == 0 else 1.055 - 0.055 * p
    cw, ch = int(W / z), int(H / z)
    x0, y0 = (W - cw) // 2, (H - ch) // 2
    return img.crop((x0, y0, x0 + cw, y0 + ch)).resize((W, H), Image.BILINEAR).convert("RGBA")


_STILLS = {}


def still(name):
    if name not in _STILLS:
        _STILLS[name] = Image.open(f"stills/{name}.jpg").convert("RGB")
    return _STILLS[name]


# ------------------------------------------------------------------ helpers
_BG = None


def background():
    global _BG
    if _BG is None:
        yy, xx = np.mgrid[0:H, 0:W].astype(np.float32)
        r = np.sqrt((xx - W * 0.5) ** 2 + (yy - H * 0.45) ** 2) / (W * 0.8)
        k = np.clip(r, 0, 1)[..., None]
        a = np.array(BG, np.float32) * (1 - 0.06 * k)
        _BG = Image.fromarray(a.astype(np.uint8)).convert("RGBA")
    return _BG.copy()


def text(d, xy, s, size, weight="Bold", fill=INK, anchor="mm", stroke=0, stroke_fill=(0, 0, 0)):
    d.text(xy, s, font=font(size, weight), fill=fill, anchor=anchor, stroke_width=stroke, stroke_fill=stroke_fill)


def wrap(s, f, maxw):
    words, lines, cur = s.split(), [], ""
    for w_ in words:
        trial = (cur + " " + w_).strip()
        if f.getlength(trial) <= maxw or not cur:
            cur = trial
        else:
            lines.append(cur)
            cur = w_
    if cur:
        lines.append(cur)
    return lines


def rrect(d, box, r, fill=None, outline=None, width=2):
    d.rounded_rectangle(box, radius=r, fill=fill, outline=outline, width=width)


def layer():
    return Image.new("RGBA", (W, H), (0, 0, 0, 0))


def fade(lay, a):
    if a >= 0.999:
        return lay
    lay = lay.copy()
    lay.putalpha(lay.getchannel("A").point(lambda v: int(v * max(0.0, a))))
    return lay


def paste_scaled(base, lay, cx, cy, s, alpha=1.0):
    if s <= 0.01 or alpha <= 0:
        return
    lay = fade(lay, alpha)
    if abs(s - 1) > 0.003:
        lay = lay.resize((max(1, int(W * s)), max(1, int(H * s))), Image.BILINEAR)
        full = layer()
        full.paste(lay, (int(cx - cx * s), int(cy - cy * s)))
        lay = full
    base.alpha_composite(lay)


def tag(img, label, cx, cy, color=TAG_RED, size=44):
    d = ImageDraw.Draw(img)
    f = font(size, "Bold")
    w_ = f.getlength(label) + 56
    d.rounded_rectangle((cx - w_ / 2, cy - size * 0.78, cx + w_ / 2, cy + size * 0.78), radius=8, fill=color)
    d.text((cx, cy + 2), label, font=f, fill=WHITE, anchor="mm")


def tag_left(img, label, x, cy, color=TAG_BLUE, size=40):
    d = ImageDraw.Draw(img)
    f = font(size, "Bold")
    w_ = f.getlength(label) + 50
    d.rounded_rectangle((x, cy - size * 0.78, x + w_, cy + size * 0.78), radius=8, fill=color)
    d.text((x + w_ / 2, cy + 2), label, font=f, fill=WHITE, anchor="mm")


# ------------------------------------------------------------------ scenes
def scene_title(sc, p, lt):
    img = background()
    d = ImageDraw.Draw(img)
    lines = sc["lines"]
    num = lines[0] if lines[0].isdigit() else None
    body = lines[1:] if num else lines
    x0 = 420 if num else 250
    if num:
        k = out_back(lt / 0.4)
        r = int(105 * k)
        d.ellipse((250 - r, H // 2 - r, 250 + r, H // 2 + r), fill=RED)
        text(d, (250, H // 2 + 6), num, int(130 * k), "Bold", WHITE)
    size = 190 if len(body) == 1 else (170 if len(body) == 2 else 150)
    widest = lambda s_: max(font(s_, "Bold").getlength(b) for b in body)  # noqa: E731
    while widest(size) > (1350 if num else 1500):
        size -= 6
    total_h = len(body) * size * 1.02
    y = H // 2 - total_h / 2 + size * 0.5 - (36 if sc.get("sub") else 0)
    for j, b in enumerate(body):
        k = out_cubic((lt - 0.1 * j - 0.05) / 0.4)
        lay = layer()
        ld = ImageDraw.Draw(lay)
        col = RED if (j == len(body) - 1 and len(body) > 1) else INK
        ld.text((x0 - (1 - k) * 90, y + j * size * 1.02), b, font=font(size, "Bold"), fill=col, anchor="lm")
        img.alpha_composite(fade(lay, k))
    if sc.get("sub"):
        k = out_cubic((lt - 0.45) / 0.45)
        yy = y + (len(body) - 1) * size * 1.02 + size * 0.62 + 24
        f = font(54, "SemiBold")
        d.rectangle((x0, yy, x0 + f.getlength(sc["sub"]) * k, yy + 7), fill=GREEN)
        lay = layer()
        ImageDraw.Draw(lay).text((x0, yy + 56), sc["sub"], font=f, fill=GRAY, anchor="lm")
        img.alpha_composite(fade(lay, k))
    return img


def sig(x):
    k = 10.0
    lo, hi = 1 / (1 + math.exp(k * 0.5)), 1 / (1 + math.exp(-k * 0.5))
    return (1 / (1 + math.exp(-k * (x - 0.5))) - lo) / (hi - lo)


CX0, CX1, CY0, CY1 = 330, 1640, 820, 190


def cpt(x):
    return CX0 + x * (CX1 - CX0), CY0 - sig(x) * (CY0 - CY1)


def slope_angle(x):
    x1, y1 = cpt(max(0, x - 0.01))
    x2, y2 = cpt(min(1, x + 0.01))
    return math.degrees(math.atan2(-(y2 - y1), x2 - x1))


def rotated_label(img, s, xy, angle, size=46, fill=GREEN):
    f = font(size, "Bold")
    w_ = int(f.getlength(s)) + 20
    lay = Image.new("RGBA", (w_, size * 2), (0, 0, 0, 0))
    ImageDraw.Draw(lay).text((w_ / 2, size), s, font=f, fill=fill, anchor="mm")
    lay = lay.rotate(angle, expand=True, resample=Image.BICUBIC)
    img.alpha_composite(lay, (int(xy[0] - lay.width / 2), int(xy[1] - lay.height / 2)))


def scene_curve(sc, p, lt, s=None):
    img = background()
    d = ImageDraw.Draw(img)
    d.line([(CX0 - 40, CY1 - 60), (CX0 - 40, CY0 + 30)], fill=INK, width=5)
    d.line([(CX0 - 40, CY0 + 30), (CX1 + 70, CY0 + 30)], fill=INK, width=5)
    text(d, ((CX0 + CX1) / 2, CY0 + 90), "TIME", 44, "Bold", INK)
    lay = Image.new("RGBA", (420, 80), (0, 0, 0, 0))
    ImageDraw.Draw(lay).text((210, 40), "PROGRESS", font=font(44, "Bold"), fill=INK, anchor="mm")
    lay = lay.rotate(90, expand=True)
    img.alpha_composite(lay, (CX0 - 140, int((CY0 + CY1) / 2) - 210))
    a, b = sc["a"], sc["b"]
    cur = a + (b - a) * ease(min(1.0, p * 1.35))
    d = ImageDraw.Draw(img)
    full = [cpt(i / 240) for i in range(241)]
    d.line(full, fill=RED, width=7, joint="curve")
    n = int(240 * cur)
    if n > 1:
        d.line(full[: n + 1], fill=GREEN, width=9, joint="curve")
    hx, hy = cpt(cur)
    d.ellipse((hx - 15, hy - 15, hx + 15, hy + 15), fill=WHITE, outline=GREEN, width=7)
    for nm, xm, off, lo in (("SLOW", 0.13, (0, -48), 0.0), ("RAPID", 0.50, (-62, 6), 0.30), ("STABLE", 0.86, (0, -50), 0.72)):
        if cur >= lo + 0.02:
            x, y = cpt(xm)
            rotated_label(img, nm, (x + off[0], y + off[1]), slope_angle(xm))
    if sc.get("label"):
        rrect(d, (CX0 + 20, 100, CX0 + 20 + 250, 170), 12, fill=INK)
        text(d, (CX0 + 145, 135), f"{sc['label']} curve", 40, "Bold", WHITE)
    names = sc.get("pip") or []
    if names and s is not None:
        j = min(len(names) - 1, int(p * len(names)))
        k = out_back((lt - 0.2) / 0.3)
        pip = frame_img(clip_dir(s, f"_pip{j}"), s["t0"] + (s["t1"] - s["t0"]) * j / len(names), s["t0"] + lt)
        pip = pip.resize((560, 315), Image.BILINEAR).convert("RGBA")
        px, py = 1180, 520
        lay = layer()
        ld = ImageDraw.Draw(lay)
        ld.rectangle((px + 8, py + 8, px + 568, py + 323), fill=(0, 0, 0, 50))
        lay.alpha_composite(pip, (px, py))
        paste_scaled(img, lay, px + 280, py + 157, 0.85 + 0.15 * min(1.0, k), min(1.0, lt / 0.2))
    return img


def scene_list(sc, p, lt):
    img = background()
    d = ImageDraw.Draw(img)
    items = sc["items"]
    head = sc.get("head")
    top = 170
    if head:
        text(d, (430, 150), head.upper(), 54, "Bold", GRAY, "lm")
        top = 270
    n = len(items)
    rowh = min(165, (H - top - 170) / n)
    for j, it in enumerate(items):
        appear = 0.06 + 0.7 * j / n
        k = out_cubic((p - appear) / 0.12)
        if k <= 0.01:
            continue
        y = top + j * rowh + rowh / 2
        lay = layer()
        ld = ImageDraw.Draw(lay)
        ld.line([(430, y + rowh / 2 - 4), (1500, y + rowh / 2 - 4)], fill=LGRAY, width=3)
        ld.ellipse((430, y - 34, 498, y + 34), fill=GREEN if j % 2 == 0 else RED)
        ld.line([(447, y), (459, y + 14), (482, y - 14)], fill=WHITE, width=9, joint="curve")
        ld.text((540, y - 2), it, font=font(88, "Bold"), fill=INK, anchor="lm")
        lay = lay.transform(lay.size, Image.AFFINE, (1, 0, (1 - k) * 80, 0, 1, 0))
        img.alpha_composite(fade(lay, k))
    return img


def scene_counter(sc, p, lt):
    img = background()
    d = ImageDraw.Draw(img)
    text(d, (W // 2, 160), sc["label"].upper(), 56, "Bold", GRAY)
    e = ease(min(1.0, p * 1.4))
    val = int(sc["to"] * e)
    cx, cy, r = W // 2, 540, 300
    d.arc((cx - r, cy - r, cx + r, cy + r), 0, 360, fill=LGRAY, width=12)
    d.arc((cx - r, cy - r, cx + r, cy + r), -90, -90 + 360 * e, fill=GREEN, width=16)
    text(d, (cx, cy - 20), f"{val}", 330, "Bold", INK)
    text(d, (cx, cy + 190), sc["unit"], 62, "SemiBold", RED)
    text(d, (W // 2, 905), sc["sub"], 50, "SemiBold", GRAY)
    return img


def scene_timeline(sc, p, lt):
    img = background()
    d = ImageDraw.Draw(img)
    items = sc["items"]
    n = len(items)
    xs = [W / 2] if n == 1 else [330 + j * (W - 660) / (n - 1) for j in range(n)]
    y = 560
    prog = ease(min(1.0, p * 1.2))
    d.line([(xs[0] - 160, y), (xs[-1] + 160, y)], fill=LGRAY, width=6)
    d.line([(xs[0] - 160, y), (xs[0] - 160 + (xs[-1] - xs[0] + 320) * prog, y)], fill=INK, width=6)
    for j, (big, cap) in enumerate(items):
        appear = 0.05 + 0.75 * j / max(1, n)
        k = out_back((p - appear) / 0.16)
        if k <= 0.02:
            continue
        lay = layer()
        ld = ImageDraw.Draw(lay)
        col = GREEN if j % 2 == 0 else RED
        x = xs[j]
        ld.ellipse((x - 22, y - 22, x + 22, y + 22), fill=col)
        size = 150 if len(big) <= 6 else 100
        ld.text((x, y - 150), big, font=font(size, "Bold"), fill=INK, anchor="mm")
        f = font(52, "SemiBold")
        for q, ln in enumerate(wrap(cap, f, 520 if n < 3 else 440)):
            ld.text((x, y + 100 + q * 62), ln, font=f, fill=GRAY, anchor="mm")
        paste_scaled(img, lay, x, y, k)
    return img


def typed(s, p):
    return s[: int(len(s) * min(1.0, max(0.0, p)))]


def scene_chat(sc, p, lt):
    img = Image.new("RGBA", (W, H), CHAT_BG + (255,))
    d = ImageDraw.Draw(img)
    f = font(50, "SemiBold")
    maxw = 1100
    pr_lines = wrap(sc["prompt"], f, maxw)
    rp_lines = wrap(sc["reply"], f, maxw)
    pr = typed(sc["prompt"], (p - 0.04) / 0.28)
    rp = typed(sc["reply"], (p - 0.42) / 0.5)
    h1 = len(pr_lines) * 66 + 120
    h2 = len(rp_lines) * 66 + 120
    y1 = 200
    d.rectangle((0, y1, W, y1 + h1), fill=CHAT_BG)
    d.rectangle((0, y1 + h1, W, y1 + h1 + h2), fill=CHAT_AI)
    d.line([(0, y1 + h1), (W, y1 + h1)], fill=(86, 88, 105), width=2)
    d.rounded_rectangle((300, y1 + 60, 352, y1 + 112), radius=8, fill=(120, 140, 210))
    d.rounded_rectangle((300, y1 + h1 + 60, 352, y1 + h1 + 112), radius=8, fill=(16, 163, 127))
    off = 0
    for q, l in enumerate(pr_lines):
        d.text((420, y1 + 60 + q * 66), pr[off: off + len(l)], font=f, fill=(236, 236, 241), anchor="lt")
        off += len(l) + 1
    if p > 0.34:
        off = 0
        for q, l in enumerate(rp_lines):
            d.text((420, y1 + h1 + 60 + q * 66), rp[off: off + len(l)], font=f, fill=(236, 236, 241), anchor="lt")
            off += len(l) + 1
        if len(rp) < len(sc["reply"]) and int(lt * 3) % 2 == 0:
            done = 0
            for q, l in enumerate(rp_lines):
                if len(rp) <= done + len(l):
                    cx_ = 420 + f.getlength(rp[done:])
                    d.rectangle((cx_ + 6, y1 + h1 + 62 + q * 66, cx_ + 24, y1 + h1 + 62 + q * 66 + 48),
                                fill=(236, 236, 241))
                    break
                done += len(l) + 1
    return img


def draw_hand(d, cx, cy, s, fingers=7, col=(214, 170, 140)):
    d.ellipse((cx - 150 * s, cy - 40 * s, cx + 150 * s, cy + 190 * s), fill=col)
    for j in range(fingers):
        a = -math.pi * (0.1 + 0.8 * j / (fingers - 1))
        L = (190 + 40 * math.sin(j * 1.9)) * s
        bx, by = cx + 110 * s * math.cos(a), cy + 20 * s + 80 * s * math.sin(a)
        ex, ey = bx + L * math.cos(a), by + L * math.sin(a)
        d.line([(bx, by), (ex, ey)], fill=col, width=int(44 * s))
        d.ellipse((ex - 22 * s, ey - 22 * s, ex + 22 * s, ey + 22 * s), fill=col)


def fit_still(name, box, zoom=1.0):
    im = still(name)
    w_, h_ = box[2] - box[0], box[3] - box[1]
    s = max(w_ / im.width, h_ / im.height) * zoom
    im = im.resize((int(im.width * s), int(im.height * s)), Image.BILINEAR)
    x0, y0 = (im.width - w_) // 2, (im.height - h_) // 2
    return im.crop((x0, y0, x0 + w_, y0 + h_)).convert("RGBA")


def scene_compare(sc, p, lt):
    img = background()
    (ly, lc), (ry, rc) = sc["left"], sc["right"]
    plain = sc.get("plain")
    video = "second" in lc
    L = (110, 250, 930, 790)
    R = (990, 250, 1810, 790)
    for side, (yr, cap), box in (("l", (ly, lc), L), ("r", (ry, rc), R)):
        appear = 0.08 if side == "l" else 0.38
        k = out_back((p - appear) / 0.2)
        if k <= 0.02:
            continue
        lay = layer()
        ld = ImageDraw.Draw(lay)
        w_, h_ = box[2] - box[0], box[3] - box[1]
        if plain:
            ld.rectangle(box, fill=WHITE, outline=LGRAY, width=3)
            f = font(76, "Bold")
            for q, ln in enumerate(wrap(cap, f, w_ - 100)):
                ld.text(((box[0] + box[2]) / 2, (box[1] + box[3]) / 2 - 40 + q * 90), ln, font=f,
                        fill=GREEN if side == "l" else RED, anchor="mm")
        elif side == "l":
            ld.rectangle(box, fill=(214, 206, 224))
            if video:
                rng = np.random.default_rng(int(lt * 8))
                bs = 40
                for gx in range(int(w_ // bs) + 1):
                    for gy in range(int(h_ // bs) + 1):
                        v = int(rng.integers(80, 190))
                        ld.rectangle((box[0] + gx * bs, box[1] + gy * bs, min(box[2], box[0] + gx * bs + bs),
                                      min(box[3], box[1] + gy * bs + bs)), fill=(v, v - 10, v + 20))
                text(ld, ((box[0] + box[2]) / 2, (box[1] + box[3]) / 2), "0:02", 150, "Bold", WHITE)
            else:
                draw_hand(ld, box[0] + w_ / 2, box[1] + h_ * 0.4, 1.0, 7)
                for j in range(6):
                    yy = box[1] + ((j * 97 + int(lt * 60)) % int(h_))
                    ld.rectangle((box[0], yy, box[2], yy + 7), fill=(160, 150, 190))
                text(ld, (box[0] + 90, box[3] - 34), "illustration", 34, "SemiBold", GRAY)
        else:
            lay.alpha_composite(fit_still(sc["still"], box, 1.0 + 0.04 * p), (box[0], box[1]))
            if video:
                for j in range(44):
                    hh = 16 + 60 * abs(math.sin(j * 0.7 + lt * 7))
                    cxx = box[0] + 30 + j * (w_ - 60) / 43
                    ld.rectangle((cxx - 4, box[3] - 30 - hh, cxx + 4, box[3] - 30), fill=WHITE)
                text(ld, (box[2] - 90, box[1] + 44), "0:30", 56, "Bold", WHITE, stroke=3)
            tag(lay, "GENERATED BY AI", (box[0] + box[2]) / 2, box[3] - 120 if not video else box[1] + 50, size=36)
        ld.text(((box[0] + box[2]) / 2, box[1] - 70), yr, font=font(104, "Bold"), fill=RED if side == "l" else GREEN,
                anchor="mm")
        if not plain:
            ld.text(((box[0] + box[2]) / 2, box[3] + 66), cap, font=font(56, "SemiBold"), fill=INK, anchor="mm")
        paste_scaled(img, lay, (box[0] + box[2]) / 2, (box[1] + box[3]) / 2, k)
    return img


def scene_aipair(sc, p, lt):
    img = Image.new("RGBA", (W, H), (0, 0, 0, 255))
    for j, nm in enumerate(sc["names"]):
        box = (0 if j == 0 else 962, 0, 958 if j == 0 else 1920, 1080)
        z = 1.0 + 0.05 * p if j == 0 else 1.05 - 0.05 * p
        im = fit_still(nm, box, z)
        k = ease((p - 0.05 - 0.12 * j) / 0.2)
        img.alpha_composite(fade(im, k), (box[0], box[1]))
        if k > 0.9:
            tag(img, "GENERATED BY AI", (box[0] + box[2]) / 2, H - 150, size=40)
    return img


def scene_bars(sc, p, lt):
    img = background()
    d = ImageDraw.Draw(img)
    text(d, (W // 2, 140), sc["head"].upper(), 56, "Bold", GRAY)
    if sc.get("doubling"):
        n = 6
        base = 800
        d.line([(300, base + 4), (1640, base + 4)], fill=INK, width=5)
        for j in range(n):
            k = out_back((p - 0.05 - j * 0.11) / 0.18)
            if k <= 0.02:
                continue
            h_ = 22 * (2 ** j) * min(1, k)
            x = 360 + j * 215
            rrect(d, (x, base - h_, x + 150, base), 6, fill=GREEN if j < 5 else RED)
            text(d, (x + 75, base + 54), f"x{2 ** j}", 48, "Bold", INK)
        text(d, (W // 2, 925), "illustrative: each step doubles", 40, "SemiBold", GRAY)
    elif sc.get("drop"):
        zero = 660
        k1 = ease((p - 0.1) / 0.3)
        k2 = ease((p - 0.4) / 0.4)
        rrect(d, (520, zero - 250 * k1, 820, zero), 6, fill=GREEN)
        rrect(d, (1100, zero, 1400, zero + 290 * k2), 6, fill=RED)
        d.line([(380, zero), (1540, zero)], fill=INK, width=5)
        text(d, (670, zero + 80), "Less exposed", 54, "Bold", INK)
        text(d, (1250, zero - 70), "Most AI-exposed", 54, "Bold", INK)
        text(d, (W // 2, 925), "illustrative: direction of change since 2022, not exact figures", 38, "SemiBold", GRAY)
    else:
        for j, (lab, frac) in enumerate(sc["items"]):
            k = ease((p - 0.08 - j * 0.12) / 0.3)
            y = 340 + j * 150
            text(d, (600, y), lab, 62, "Bold", INK, "rm")
            rrect(d, (640, y - 34, 640 + 960 * frac * k, y + 34), 6, fill=GREEN if j % 2 == 0 else RED)
    return img


def scene_stat(sc, p, lt):
    img = background()
    d = ImageDraw.Draw(img)
    big = sc["big"]
    size = 430
    while font(size, "Bold").getlength(big) > 1650:
        size -= 10
    k = out_back(lt / 0.4)
    lay = layer()
    ImageDraw.Draw(lay).text((W // 2, H // 2 - 70), big, font=font(size, "Bold"), fill=INK, anchor="mm")
    paste_scaled(img, lay, W // 2, H // 2 - 70, 0.6 + 0.4 * min(1.1, k), min(1.0, lt / 0.2))
    bw = font(size, "Bold").getlength(big) * ease((lt - 0.2) / 0.5)
    yy = H // 2 + size * 0.34
    d.rectangle((W // 2 - bw / 2, yy, W // 2 + bw / 2, yy + 12), fill=GREEN)
    a = ease((lt - 0.45) / 0.4)
    lay = layer()
    ImageDraw.Draw(lay).text((W // 2, yy + 90), sc["small"], font=font(78, "SemiBold"), fill=RED, anchor="mm")
    img.alpha_composite(fade(lay, a))
    return img


def scene_wave(sc, p, lt):
    img = background()
    d = ImageDraw.Draw(img)
    text(d, (W // 2, 170), sc["label"].upper(), 60, "Bold", GRAY)
    n = 72
    for row, (cy, col, show) in enumerate(((470, INK, True), (770, GREEN, p > 0.4))):
        if not show:
            continue
        for j in range(n):
            amp = abs(math.sin(j * 0.45 + lt * (6 + row * 2)) * math.sin(j * 0.13 + lt * 3 + row)) * 125 + 10
            x = 190 + j * (W - 380) / (n - 1)
            d.rounded_rectangle((x - 8, cy - amp, x + 8, cy + amp), radius=8, fill=col)
    text(d, (W // 2, 905), "original  |  copy" if p > 0.4 else "original", 46, "SemiBold", GRAY)
    return img


_NODES = None


def scene_network(sc, p, lt):
    global _NODES
    img = background()
    d = ImageDraw.Draw(img)
    layers = [4, 6, 6, 3]
    if _NODES is None:
        _NODES = [[(330 + li * 420, 230 + (j + 0.5) * 540 / n) for j in range(n)] for li, n in enumerate(layers)]
    for li in range(len(layers) - 1):
        for a_ in _NODES[li]:
            for b_ in _NODES[li + 1]:
                d.line([a_, b_], fill=LGRAY, width=2)
    for li in range(len(layers) - 1):
        for ia, a_ in enumerate(_NODES[li]):
            for ib, b_ in enumerate(_NODES[li + 1]):
                ph = (lt * 0.9 + (ia * 7 + ib * 3 + li * 5) * 0.137) % 1.0
                if ph < 0.35:
                    t_ = ph / 0.35
                    x, y = a_[0] + (b_[0] - a_[0]) * t_, a_[1] + (b_[1] - a_[1]) * t_
                    d.ellipse((x - 7, y - 7, x + 7, y + 7), fill=RED)
    for li, ns in enumerate(_NODES):
        for j, (x, y) in enumerate(ns):
            glow = 0.5 + 0.5 * math.sin(lt * 3 + li + j)
            r = 24
            d.ellipse((x - r, y - r, x + r, y + r), fill=WHITE, outline=GREEN if glow > 0.5 else INK, width=6)
    k = out_back(lt / 0.5)
    lay = layer()
    ImageDraw.Draw(lay).text((W // 2, 900), sc["label"], font=font(120, "Bold"), fill=INK, anchor="mm")
    paste_scaled(img, lay, W // 2, 900, 0.7 + 0.3 * min(1.0, k), min(1.0, lt / 0.25))
    return img


def scene_quote(sc, p, lt):
    img = background()
    d = ImageDraw.Draw(img)
    f = font(150, "Bold")
    lines = wrap(sc["text"], f, 1500)
    text(d, (W // 2, 250), "“", 420, "Bold", RED)
    shown = typed(sc["text"], (p - 0.05) / 0.55)
    y0 = H // 2 - (len(lines) - 1) * 86 + 40
    off = 0
    for q, l in enumerate(lines):
        d.text((W // 2, y0 + q * 172), shown[off: off + len(l)], font=f, fill=INK, anchor="mm")
        off += len(l) + 1
    return img


def scene_endcard(sc, p, lt):
    img = background()
    rows = ["COMMENT", "LIKE", "SHARE", "SUBSCRIBE"]
    for j, r_ in enumerate(rows):
        k = out_cubic((lt - 0.3 - 0.25 * j) / 0.4)
        lay = layer()
        ld = ImageDraw.Draw(lay)
        y = 330 + j * 150
        x = 200
        if j == 0:
            rrect(ld, (x, y - 34, x + 78, y + 26), 18, outline=RED, width=7)
            ld.polygon([(x + 16, y + 24), (x + 12, y + 52), (x + 42, y + 26)], fill=RED)
        elif j == 1:
            ld.rounded_rectangle((x, y - 6, x + 26, y + 40), radius=4, fill=RED)
            ld.polygon([(x + 34, y - 4), (x + 52, y - 36), (x + 66, y - 28), (x + 60, y - 4), (x + 86, y - 4),
                        (x + 82, y + 38), (x + 34, y + 40)], fill=RED)
        elif j == 2:
            pts = [(x + 12, y), (x + 70, y - 30), (x + 70, y + 30)]
            ld.line([pts[0], pts[1]], fill=RED, width=7)
            ld.line([pts[0], pts[2]], fill=RED, width=7)
            for q in pts:
                ld.ellipse((q[0] - 12, q[1] - 12, q[0] + 12, q[1] + 12), fill=RED)
        else:
            ld.ellipse((x, y - 40, x + 80, y + 40), outline=RED, width=7)
            ld.polygon([(x + 30, y - 18), (x + 30, y + 18), (x + 62, y)], fill=RED)
        ld.text((x + 130, y), r_, font=font(80, "Bold"), fill=RED, anchor="lm")
        lay = lay.transform(lay.size, Image.AFFINE, (1, 0, (1 - k) * 100, 0, 1, 0))
        img.alpha_composite(fade(lay, k))
    k = ease((lt - 0.6) / 0.6)
    glow = layer()
    gd = ImageDraw.Draw(glow)
    gd.ellipse((1330, 150, 1670, 490), outline=(70, 130, 255, 255), width=14)
    gd.rounded_rectangle((1130, 560, 1730, 900), radius=22, outline=(235, 60, 70, 255), width=14)
    img.alpha_composite(fade(glow.filter(ImageFilter.GaussianBlur(14)), 0.8 * k))
    img.alpha_composite(fade(glow, k))
    d = ImageDraw.Draw(img)
    text(d, (1500, 105), "Subscribe", 56, "SemiBold", INK, "mm")
    text(d, (1430, 960), "Next video", 56, "SemiBold", INK, "mm")
    return img


SCENES = dict(title=scene_title, curve=scene_curve, list=scene_list, counter=scene_counter, timeline=scene_timeline,
              chat=scene_chat, compare=scene_compare, aipair=scene_aipair, bars=scene_bars, stat=scene_stat,
              wave=scene_wave, network=scene_network, quote=scene_quote, endcard=scene_endcard)


# ------------------------------------------------------------------ subtitles
def build_cues(max_words=8):
    cues = []
    for i, line in enumerate(LINES):
        words = line.split()
        n = math.ceil(len(words) / max_words)
        size = len(words) / n
        bounds = [round(size * k) for k in range(n + 1)]
        for j, k in zip(bounds[:-1], bounds[1:]):
            t0 = starts[i] + TW[i][j] - 0.08
            t1 = starts[i] + TW[i][k] - 0.05 if k < len(words) else starts[i] + D[i] + 0.25
            cues.append((t0, t1, " ".join(words[j:k])))
    return cues


CUES = build_cues()


def subtitles(img, t):
    for t0, t1, txt in CUES:
        if t0 <= t < t1:
            f = font(40, "SemiBold")
            w_ = f.getlength(txt)
            y = H - 60
            lay = Image.new("RGBA", (W, H), (0, 0, 0, 0))
            d = ImageDraw.Draw(lay)
            d.rounded_rectangle((W / 2 - w_ / 2 - 18, y - 28, W / 2 + w_ / 2 + 18, y + 28), radius=10,
                                fill=(0, 0, 0, 120))
            d.text((W / 2, y + 1), txt, font=f, fill=(255, 255, 255, 240), anchor="mm")
            img.alpha_composite(lay)
            return


def frame(fi):
    t = fi / FPS
    s = shot_at(t)
    sc = s["sc"]
    p = (t - s["t0"]) / max(0.01, s["t1"] - s["t0"])
    lt = t - s["t0"]
    kind = sc["t"]
    if kind == "clip":
        img = clip_frame(s, t)
        if sc["src"].startswith("gen:"):
            tag(img, "GENERATED BY AI", W // 2, H - 150)
        if sc.get("tag") == "script":
            tag_left(img, "SCRIPT WRITTEN WITH AI", 70, H - 150)
    else:
        img = SCENES[kind](sc, p, lt, s) if kind == "curve" else SCENES[kind](sc, p, lt)
        if kind not in ("aipair", "chat", "endcard"):
            z = 1.0 + 0.022 * p  # slow push-in so graphics are never static
            cw, ch = int(W / z), int(H / z)
            x0, y0 = (W - cw) // 2, (H - ch) // 2
            img = img.crop((x0, y0, x0 + cw, y0 + ch)).resize((W, H), Image.BILINEAR)
        if kind == "chat":
            tag(img, "GENERATED BY AI", W // 2, H - 150)
    if kind != "endcard":
        subtitles(img, t)
    return img.convert("RGB")


if __name__ == "__main__":
    cmd = sys.argv[1]
    if cmd == "prep":
        prep()
    elif cmd == "info":
        print("frames", NF, "total", round(TOTAL, 1), "shots", len(SHOTS))
        from collections import Counter
        print(Counter(s["sc"]["t"] for s in SHOTS))
        print("avg shot", round(TOTAL / len(SHOTS), 1), "longest", max(round(s["t1"] - s["t0"], 1) for s in SHOTS))
    elif cmd == "still":
        frame(int(sys.argv[2])).save(f"still_{sys.argv[2]}.png")
    elif cmd == "video":
        a, b, out = int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
        p = subprocess.Popen(["ffmpeg", "-y", "-loglevel", "error", "-f", "rawvideo", "-pix_fmt", "rgb24", "-s",
                              f"{W}x{H}", "-r", str(FPS), "-i", "-", "-c:v", "libx264", "-preset", "fast", "-crf", "18",
                              "-pix_fmt", "yuv420p", out], stdin=subprocess.PIPE)
        for fi in range(a, b):
            p.stdin.write(frame(fi).tobytes())
            if fi % 60 == 0:
                print(fi, flush=True)
        p.stdin.close()
        p.wait()
