"""'Could You Spend $100 Billion?' long-form (16:9), jack pockets visual language.
Each entry: (narration, scene). Scene types: slab, photo, card, stack, years, failed, spot, checkout, chart, count.
Money values are running totals of what has been spent (USD)."""

B = 1_000_000_000
M = 1_000_000

S = [
    # ------------------------------------------------------------ intro
    ("Imagine you wake up tomorrow, and there's a hundred billion dollars in your bank account.",
     dict(t="slab", spent=0, note="your balance", phone=True)),
    ("Not a hundred million. Not one billion. A hundred billion.",
     dict(t="card", lines=["$100,000,000", "$1,000,000,000", "$100,000,000,000"], strike=[0, 1], bg="white")),
    ("That's more than the entire yearly economy of over half the countries on Earth.",
     dict(t="card", lines=["> yearly gdp of", "over half the world's countries"], bg="white", arrow=True)),
    ("Your phone won't stop ringing. Your bank, financial advisers, and relatives you didn't know you had.",
     dict(t="card", lines=["missed calls (47)", "bank", "advisers", "cousin?"], bg="black", steps=["bank", "advisers", "relatives"])),
    ("There's only one rule. You have to spend all of it. No saving, no investing, and no giving it away until the very end.",
     dict(t="card", lines=["rules:", "1. spend it all", "2. no investing", "3. no giving it away (yet)"], bg="white", steps=["rule", "saving", "investing", "giving"])),
    ("Sounds easy, right? It's not even close.",
     dict(t="card", lines=["easy?"], bg="black", arrow=True)),
    ("Because first, you need to understand how much money this actually is.",
     dict(t="slab", spent=0, zoom=0.85)),
    # ------------------------------------------------------------ scale
    ("If you stacked one million dollars in hundred dollar bills, the pile would be just over a meter tall.",
     dict(t="stack", height_m=1.1, ref="human", label="$1,000,000")),
    ("A billion dollars in the same bills would rise more than a kilometer into the sky, taller than the Burj Khalifa.",
     dict(t="stack", height_m=1100, ref="burj", label="$1,000,000,000")),
    ("And a hundred billion? A stack around a hundred and ten kilometers high. Higher than the line where space is often said to begin.",
     dict(t="stack", height_m=110000, ref="space", label="$100,000,000,000")),
    ("It would weigh around a thousand tonnes.",
     dict(t="count", value=1000, fmt="≈{:,} tonnes", sub="one billion bills, about a gram each")),
    ("Laid end to end, those bills would stretch around the Earth almost four times.",
     dict(t="count", value=156000, fmt="≈{:,} km", sub="Earth's circumference: 40,075 km")),
    ("And if you counted one bill every second, without sleeping, it would take you about thirty-two years.",
     dict(t="years", value=32, label="counting 1 bill per second")),
    ("Spend it at one dollar per second, and you'd need more than three thousand years.",
     dict(t="years", value=3170, label="$1 per second")),
    ("Or think of it this way. If you spent one million dollars every single day, it would take you about two hundred and seventy-four years to run out.",
     dict(t="years", value=274, label="spending $1,000,000 a day")),
    ("The average American worker earns around sixty thousand dollars a year.",
     dict(t="people", n=1, label="you: ≈$60,000 / year")),
    ("To earn a hundred billion at that salary, you would have to work for more than one and a half million years.",
     dict(t="years", value=1_666_666, label="years of work at $60k")),
    ("That's longer than our species has existed.",
     dict(t="card", lines=["homo sapiens: ≈300,000 years"], bg="white", arrow=True)),
    ("So, let's start spending.",
     dict(t="slab", spent=0, note="let's go")),
    # ------------------------------------------------------------ cars
    ("First, the obvious stuff. Cars.",
     dict(t="photo", key="lambo", label="the garage", plain=True)),
    ("A Lamborghini Aventador costs around half a million dollars. You buy ten, one in every color.",
     dict(t="photo", key="lambo", label="lamborghini aventador", price="$500k each", pt="half", buy="ten", grid=10, cost=5 * M)),
    ("A Bugatti Chiron is about three million. You take five.",
     dict(t="photo", key="bugatti", label="bugatti chiron", price="$3m each", pt="three", buy="five", grid=5, cost=15 * M)),
    ("And then the most expensive car ever sold. A 1955 Mercedes-Benz 300 SLR, auctioned in 2022 for about a hundred and forty-three million dollars.",
     dict(t="photo", key="mercedes", label="1955 mercedes-benz 300 slr", price="$143m", pt="hundred", buy="dollars", cost=143 * M)),
    ("Your garage is now worth more than most skyscrapers. And you've spent less than two tenths of one percent.",
     dict(t="slab", note="0.16% spent")),
    # ------------------------------------------------------------ homes
    ("So you need somewhere to park all of this.",
     dict(t="photo", key="la", label="los angeles", plain=True)),
    ("In Los Angeles, a mega mansion called The One sold for about a hundred and forty-one million dollars.",
     dict(t="photo", key="la", label="los angeles", price="$141m", pt="hundred", buy="dollars", cost=141 * M)),
    ("In New York, a penthouse overlooking Central Park went for around two hundred and thirty-eight million.",
     dict(t="photo", key="cps", label="220 central park south", price="$238m", pt="two", buy="million", cost=238 * M)),
    ("Add a private island in the Bahamas for, let's say, fifty million, and you have places to stay.",
     dict(t="photo", key="island", label="private island", price="≈$50m", pt="fifty", buy="stay", cost=50 * M)),
    ("Running total, about five hundred and ninety-two million dollars.",
     dict(t="slab", note="≈ $592m spent")),
    ("Still not even one percent.",
     dict(t="card", lines=["< 1%"], bg="white", arrow=True)),
    # ------------------------------------------------------------ travel
    ("Next, you need a way to get between them.",
     dict(t="photo", key="jet", label="", plain=True)),
    ("A Gulfstream G650 private jet, around seventy million.",
     dict(t="photo", key="jet", label="gulfstream g650", price="$70m", pt="seventy", buy="million", cost=70 * M)),
    ("But why stop there? A Boeing 747 turned into a flying palace can cost well over four hundred million dollars.",
     dict(t="photo", key="b747", label="boeing 747 (vip)", price="$400m+", pt="four", buy="dollars", cost=400 * M)),
    ("And for the ocean, a superyacht. The biggest ones cost around half a billion dollars. You order one.",
     dict(t="photo", key="yacht", label="superyacht", price="≈$500m", pt="half", buy="order", cost=500 * M)),
    ("And keeping a superyacht running can cost around ten percent of its price every year. That's tens of millions, just for crew, fuel and repairs.",
     dict(t="count", value=50 * M, fmt="≈${:,} / year", sub="crew, fuel, repairs")),
    ("Total so far, about one point six billion.",
     dict(t="slab", note="≈ $1.6B spent")),
    ("And your money has barely noticed.",
     dict(t="card", lines=["(it barely noticed)"], bg="white")),
    # ------------------------------------------------------------ daily life
    ("But you still have to live. So let's upgrade your daily life.",
     dict(t="card", lines=["daily life"], bg="white")),
    ("You hire a private chef, a driver, and a full security team. That's maybe a few million dollars a year.",
     dict(t="people", n=12, label="chef, driver, security")),
    ("You eat at the best restaurants on the planet every single night, at around a thousand dollars a meal.",
     dict(t="count", value=365_000, fmt="${:,} / year", sub="$1,000 × 365 nights")),
    ("Do that for the next sixty years and you'd spend about twenty-two million dollars. On dinner.",
     dict(t="count", value=21_900_000, fmt="${:,}", sub="60 years of dinners", cost=22 * M)),
    ("A new designer outfit every day for the rest of your life? Maybe another fifty million.",
     dict(t="count", value=50 * M, fmt="≈${:,}", sub="your wardrobe", cost=50 * M)),
    ("Then a personal trainer, a doctor on call, a stylist, and a pilot on standby, twenty-four hours a day.",
     dict(t="people", n=24, label="your entourage")),
    ("Every birthday, you fly in the biggest artists in the world to play just for you. That can easily cost several million dollars a night.",
     dict(t="count", value=5 * M, fmt="≈${:,}", sub="one birthday party")),
    ("And every summer, you rent out an entire luxury resort, just so nobody else is there.",
     dict(t="photo", key="island", label="(all yours)", plain=True)),
    ("All of that luxury together barely moves the counter.",
     dict(t="slab", note="barely moved")),
    # ------------------------------------------------------------ collectibles
    ("So let's start collecting the rarest things money can buy.",
     dict(t="card", lines=["collectibles"], bg="black")),
    ("The most expensive wristwatch ever sold, a Patek Philippe Grandmaster Chime, went for about thirty-one million dollars in 2019.",
     dict(t="spot", icon="watch", label="patek philippe grandmaster chime", price="$31m", pt="thirty", buy="dollars", cost=31 * M)),
    ("The Pink Star, one of the most famous diamonds in the world, sold for about seventy-one million.",
     dict(t="spot", icon="diamond", label="the pink star diamond", price="$71.2m", pt="seventy", buy="million", cost=71 * M)),
    ("A 1952 Mickey Mantle baseball card sold for twelve point six million dollars.",
     dict(t="spot", icon="card", label="1952 topps mickey mantle", price="$12.6m", pt="twelve", buy="dollars", cost=13 * M)),
    ("And the first Superman comic, Action Comics number one, sold for six million dollars in 2024.",
     dict(t="spot", icon="comic", label="action comics #1", price="$6m", pt="six", buy="2024", cost=6 * M)),
    ("You buy them all. Your collection is now world famous, and it cost you about a hundred and twenty million.",
     dict(t="slab", note="+ $120m")),
    # ------------------------------------------------------------ real estate
    ("Then you decide to become a landlord.",
     dict(t="photo", key="suburb", label="", plain=True)),
    ("The typical American home costs around four hundred thousand dollars. You buy a thousand of them.",
     dict(t="photo", key="suburb", label="a typical home", price="≈$400k each", pt="four", buy="thousand", grid=40, cost=400 * M)),
    ("That's a whole town, for four hundred million dollars. And you've now spent about two percent.",
     dict(t="slab", note="≈ 2% spent")),
    # ------------------------------------------------------------ sports
    ("Time to think bigger. Why buy a ticket, when you can buy the whole team?",
     dict(t="photo", key="nfl", label="", plain=True)),
    ("In 2023, the Washington Commanders sold for about six billion dollars, a record for an American sports team at the time.",
     dict(t="photo", key="nfl", label="washington commanders", price="$6.05B", pt="six", buy="record", cost=6_050 * M)),
    ("In 2022, Chelsea Football Club was sold for over four billion pounds. That's around five billion dollars.",
     dict(t="photo", key="chelsea", label="stamford bridge, chelsea fc", price="≈$5B", pt="five", buy="dollars", cost=5_000 * M)),
    ("And in 2025, the Boston Celtics were sold for about six billion dollars.",
     dict(t="photo", key="celtics", label="td garden, boston celtics", price="$6.1B", pt="six", buy="dollars", cost=6_100 * M)),
    ("You buy all three. An American football team, an English football club, and a basketball dynasty.",
     dict(t="card", lines=["owner of:", "the commanders", "chelsea fc", "the celtics"], bg="white", steps=["American", "English", "basketball"])),
    ("That's another seventeen billion dollars.",
     dict(t="count", value=17_150 * M, fmt="${:,}", sub="three teams")),
    ("And for the first time, the block actually looks smaller.",
     dict(t="slab", note="≈ $19.3B spent")),
    # ------------------------------------------------------------ famous things
    ("What about buying a whole company? In 2022, Twitter was bought for about forty-four billion dollars.",
     dict(t="count", value=44 * B, fmt="${:,}", sub="twitter, 2022")),
    ("That would wipe out almost half of your fortune in a single deal.",
     dict(t="slab", spent_override=44 * B, note="≈ 44%")),
    ("But buying a company counts as investing. Rule number two. Transaction denied.",
     dict(t="failed", key=None, label="rule #2: no investing", at="Transaction")),
    ("Now let's buy something famous.",
     dict(t="photo", key="louvre", label="the louvre, paris", plain=True)),
    ("The Mona Lisa? Not for sale. It belongs to France, and French law doesn't allow national museum collections to be sold.",
     dict(t="failed", key="louvre", label="mona lisa", at="sale")),
    ("Okay. How about Leonardo's other masterpiece, Salvator Mundi? It sold for four hundred and fifty million dollars in 2017, the most ever paid for a painting.",
     dict(t="spot", label="salvator mundi", price="$450.3m", pt="four", buy="painting", cost=450 * M)),
    ("Bought. Even though it hasn't been shown in public since.",
     dict(t="spot", label="salvator mundi", price="(not seen in public since)", pt="Bought", buy=None, note=True)),
    ("What about the tallest building on Earth? The Burj Khalifa cost around one and a half billion dollars to build.",
     dict(t="photo", key="burj", label="burj khalifa, 828 m", price="≈$1.5B", pt="one", buy="build", cost=1_500 * M)),
    ("It's not for sale either. But for the same money, you could build your own.",
     dict(t="card", lines=["not for sale", "so: build your own"], bg="black", steps=["sale", "build"])),
    ("And in Las Vegas, the Sphere cost about two point three billion dollars. Now it shows whatever you want.",
     dict(t="photo", key="sphere", label="sphere, las vegas", price="$2.3B", pt="two", buy="dollars", cost=2_300 * M)),
    ("Running total, about twenty-three and a half billion.",
     dict(t="slab", note="≈ $23.5B spent")),
    # ------------------------------------------------------------ sea, air, space
    ("Let's go even bigger.",
     dict(t="photo", key="ship", label="", plain=True)),
    ("The world's largest cruise ship, Icon of the Seas, cost about two billion dollars, and can carry more than seven thousand passengers.",
     dict(t="photo", key="ship", label="icon of the seas", price="≈$2B", pt="two", buy="passengers", cost=2_000 * M)),
    ("You buy it, just for your friends.",
     dict(t="card", lines=["(for your friends)"], bg="white")),
    ("Want your own air force? An F-35 fighter jet costs around eighty million dollars. You get twenty.",
     dict(t="photo", key="f35", label="f-35 lightning ii", price="≈$80m each", pt="eighty", buy="twenty", grid=20, cost=1_600 * M)),
    ("And to carry them, the most advanced aircraft carrier ever built, the USS Gerald R. Ford, at roughly thirteen billion dollars.",
     dict(t="photo", key="carrier", label="uss gerald r. ford", price="≈$13B", pt="thirteen", buy="dollars", cost=13_000 * M)),
    ("Of course, governments don't actually sell these. But this is your fantasy.",
     dict(t="card", lines=["(hypothetically)"], bg="black")),
    ("Then, space. A private seat on a mission to the International Space Station costs around fifty-five million dollars.",
     dict(t="photo", key="iss", label="international space station", price="≈$55m / seat", pt="fifty", buy="dollars", cost=0)),
    ("You book one for yourself, and ten of your friends.",
     dict(t="photo", key="iss", label="international space station", price="11 seats = $605m", pt="book", buy="friends", cost=605 * M)),
    ("Or skip the waiting list. A whole SpaceX Falcon 9 launch is listed at around seventy million dollars.",
     dict(t="photo", key="rocket", label="spacex falcon 9", price="≈$70m / launch", pt="seventy", buy="dollars", cost=70 * M)),
    ("So you launch your own satellite, with your name on it.",
     dict(t="card", lines=["(your satellite)"], bg="black")),
    ("Total spent, a little over forty billion dollars.",
     dict(t="slab", note="≈ $40.8B spent")),
    ("Around fifty-nine billion left. And this is where things get strange.",
     dict(t="card", lines=["catch:"], bg="black", arrow=True)),
    # ------------------------------------------------------------ the catch
    ("Remember, a hundred billion dollars doesn't just sit there.",
     dict(t="slab", note="it grows")),
    ("Even in a simple savings account paying four percent, what's left earns about two point four billion dollars a year.",
     dict(t="count", value=2_400 * M, fmt="+${:,} / year", sub="4% on ≈$59,000,000,000", green=True)),
    ("That's about six and a half million dollars a day.",
     dict(t="count", value=6_575_000, fmt="+${:,} / day", sub="", green=True)),
    ("Or roughly seventy-five dollars every second.",
     dict(t="tick", rate=75, label="+${:,}", sub="every second since this sentence started")),
    ("Every minute you spend deciding what to buy next, you earn about four and a half thousand dollars.",
     dict(t="tick", rate=75, label="+${:,}", sub="per minute: ≈ $4,500")),
    ("While you were busy buying that aircraft carrier, the bank was quietly paying you back.",
     dict(t="photo", key="bank", label="your bank", plain=True)),
    ("And it compounds. At four percent, money roughly doubles every eighteen years.",
     dict(t="chart", mode="double")),
    ("Leave the remaining fifty-nine billion alone for eighteen years, and it grows past a hundred billion again.",
     dict(t="count", value=118 * B, fmt="≈${:,}", sub="after ~18 years at 4%", green=True)),
    ("Here's another way to see it.",
     dict(t="card", lines=["another way:"], bg="white")),
    ("If you spent ten million dollars every single day, your money would still last about twenty-six years.",
     dict(t="years", value=26, label="spending $10,000,000 a day")),
    ("And if you only spent five million a day, it would never run out at all. The interest would keep refilling it.",
     dict(t="chart", mode="flat")),
    ("To actually run out, you have to spend faster than the money grows.",
     dict(t="chart", mode="race")),
    ("So you hire people. A team to run your homes, your jets, your yacht and your teams.",
     dict(t="people", n=200, label="your staff")),
    ("Say ten thousand employees, at a hundred thousand dollars a year each. That's a billion dollars, every single year.",
     dict(t="count", value=1_000 * M, fmt="-${:,} / year", sub="10,000 staff × $100,000")),
    ("Your stadiums, your ship and your carrier also cost money to run. Operating an aircraft carrier alone can cost hundreds of millions per year.",
     dict(t="photo", key="carrier", label="operating costs", price="$$$ / year", pt="hundreds", buy=None)),
    ("Even with all of that, your spending only just keeps up with the interest.",
     dict(t="chart", mode="flat")),
    ("To truly empty the account, you need projects so huge that usually only countries attempt them.",
     dict(t="card", lines=["country-sized projects"], bg="white")),
    # ------------------------------------------------------------ megaprojects
    ("Like building a brand new city.",
     dict(t="photo", key="desert", label="", plain=True)),
    ("Saudi Arabia's Neom project was announced with a price tag of around five hundred billion dollars.",
     dict(t="failed", key="desert", label="neom, saudi arabia", at="five", text="$500B > your $100B")),
    ("Even your entire fortune would cover just a fraction of it.",
     dict(t="card", lines=["1/5"], bg="white", arrow=True)),
    ("Or think about the Moon. NASA's Artemis program is estimated to cost around ninety-three billion dollars through 2025.",
     dict(t="photo", key="moon", label="artemis program", price="≈$93B", pt="ninety", buy=None)),
    ("That's almost exactly the fortune you started with.",
     dict(t="slab", spent_override=93 * B, note="≈ one artemis program")),
    ("Suddenly, a hundred billion dollars doesn't feel infinite anymore.",
     dict(t="slab", note="not infinite")),
    # ------------------------------------------------------------ doing good
    ("So what if you spent it on something else?",
     dict(t="card", lines=["something else?"], bg="white")),
    ("In 2021, the head of the UN World Food Programme said about six billion dollars could help around forty-two million people on the brink of famine.",
     dict(t="people", n=420, label="≈42,000,000 people", green=True)),
    ("That's six percent of your money.",
     dict(t="slab", spent_override=6 * B, note="6%")),
    ("A mosquito net to protect against malaria costs just a few dollars. One billion dollars could buy hundreds of millions of them.",
     dict(t="count", value=300 * M, fmt="≈{:,} nets", sub="at roughly $3 each")),
    ("For the price of a single Lamborghini, you could fund dozens of water wells for villages.",
     dict(t="people", n=60, label="dozens of village wells", green=True)),
    ("Vaccines, clean water, schools. The same money that bought a stadium could change millions of lives.",
     dict(t="card", lines=["vaccines", "clean water", "schools"], bg="white", steps=["Vaccines", "clean", "schools"])),
    ("Which is exactly what some billionaires say they plan to do with most of their wealth.",
     dict(t="card", lines=["the giving pledge"], bg="black")),
    ("But the rule was, no giving it away until the end.",
     dict(t="card", lines=["rule 3"], bg="white", arrow=True)),
    # ------------------------------------------------------------ real billionaires
    ("And here's something most people miss.",
     dict(t="card", lines=["catch #2:"], bg="black", arrow=True)),
    ("Real billionaires almost never have a hundred billion dollars sitting in cash.",
     dict(t="photo", key="cash", label="(not in cash)", plain=True)),
    ("Most of their wealth is shares in the companies they built. If they tried to sell everything at once, the price would fall.",
     dict(t="chart", mode="crash")),
    ("So they borrow against those shares instead, and the shares keep growing in the background.",
     dict(t="chart", mode="borrow")),
    ("Their fortunes can rise or fall by billions in a single day, just because a stock price moved.",
     dict(t="chart", mode="volatile")),
    ("History has seen fortunes like this before. Adjusted for inflation, John D. Rockefeller's wealth is often estimated at several hundred billion dollars.",
     dict(t="count", value=400 * B, fmt="≈${:,}", sub="rockefeller, in today's dollars (est.)")),
    ("And Mansa Musa, the medieval ruler of Mali, is said to have been so rich that historians can't even put a number on it.",
     dict(t="card", lines=["mansa musa:", "\"too rich to count\""], bg="black", steps=["Mansa", "historians"])),
    ("Which is why the richest people on Earth can spend wildly, and still get richer.",
     dict(t="slab", note="still growing")),
    # ------------------------------------------------------------ the bill
    ("So let's add everything up.",
     dict(t="checkout")),
    ("Cars, homes, jets, a superyacht, three sports teams, a painting, the Sphere, a cruise ship, an air force, an aircraft carrier, and a trip to space.",
     dict(t="checkout", scroll=True)),
    ("A little over forty billion dollars.",
     dict(t="checkout", total=True)),
    ("Then the staff, the running costs, and a lifetime of interest working against you.",
     dict(t="chart", mode="flat")),
    ("Could you spend a hundred billion dollars? Technically, yes.",
     dict(t="slab", note="technically: yes")),
    ("But only if you go far beyond anything a normal person could ever imagine.",
     dict(t="stack", height_m=110000, ref="space", label="$100,000,000,000")),
    ("And here's the craziest part. Several people on Earth are already worth more than that.",
     dict(t="people", n=9, label="worth > $100B", green=True)),
    ("For them, this isn't a fantasy. It's just a Tuesday.",
     dict(t="card", lines=["just a tuesday."], bg="black")),
    ("We bought supercars, mansions, jets, yachts, teams, a painting, a rocket launch and an aircraft carrier.",
     dict(t="checkout", scroll=True)),
    ("And the hardest part wasn't finding things to buy. It was outrunning the money itself.",
     dict(t="chart", mode="race")),
    ("If you had to pick just three things from this whole list, which would they be?",
     dict(t="card", lines=["pick 3"], bg="white", arrow=True)),
    ("So tell me in the comments. What's the first thing you would buy?",
     dict(t="card", lines=["comment:", "first thing you'd buy?"], bg="white", arrow=True)),
    ("And if you enjoyed this, subscribe. Next time, we'll find out what it really takes to become a billionaire.",
     dict(t="end")),
]
LINES = [s for s, _ in S]
SCENES = [d for _, d in S]
CONT = set()
